### ISSUE TITLE
App Store？

### ISSUE THREAD

**Issue by liraku** [Sweeper777/DebtCollector#1]
hello
I like your project
Can I download it on the App Store? I want to download it and share it with my friends

**Comment by Sweeper777** [comment]
I tried to put it on the app store, but Apple rejected it. They apparently thought it was an app used to acquire (as opposed to just _record_) loans, and said that I don't have permission from financial organisations... 😞 

You can clone the repo and build it if you want.
[On the other hand, most of my other iOS projects are on the app store.](https://apps.apple.com/us/developer/xiu-cheng/id1072718085?ls=1#see-all/i-phonei-pad-apps) The name of the repo might be a little different, but it should be obvious which one is which.

**Comment by liraku** [comment]
thank you !
